import './globals.css';
import type { Metadata } from 'next';
import { Inter, Roboto, Poppins } from 'next/font/google';
import { Providers } from './providers';

const inter = Inter({ subsets: ['latin'], weight: ["400", "500", "600"], variable: '--font-inter' });
const poppins = Poppins({ subsets: ['latin'], weight: ["500", "600"], variable: '--font-poppins' });
const roboto = Roboto({ subsets: ['latin'], weight: ["400", "500", "700", "900"], variable: '--font-roboto' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout ({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className='light'>
      <body className={`${inter.variable}`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
